[build]
  command = "npm run build"
  environment = { CI = "false" }
  publish = "build"

[context.production.environment]
  REACT_APP_PEXELS_API_KEY = "84CptlFQLYfWj0euXgTzdGohgvSjyaG03MDtDgTLnK6CITNCybJKGjTZ"
  BROWSER = "none"
